language: go

matrix:
  include:
    - go: "1.10.x"
    - go: "1.11.x"
    - go: "1.12.x"
      env: RUN_SNYK=true

before_install:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then sudo apt-get install -y nodejs; fi"
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then npm install -g snyk; fi"

install:
  - go get -t ./...
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi"

script: go test -v ./...

after_success:
  - "if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $RUN_SNYK && $SNYK_TOKEN ]]; then snyk monitor --org=maxmind --project-name=maxmind/geoipupdate2; fi"

env:
  global:
    secure: "lqMoEipm/JszLrRFIxrfgIxczRIeBDBJLzpphS0wH2o4t9c1SesGPPmr0wfk6uf6yOjFCPHTuMpgex8jsXbpUc6Jf+FDC1eQZLWnV2Ve4/gdC20W0N96sdBzHcjGR6euYWPi7vzfE/3VAqgrS1Vbswc54vPVMEYGzSoNIaBP09Q3/xAuNNTRVGyEVF7POFv606gZ8sN+RR+081GhxRbzkmYAnfO/csdDRdag/yMlASVgYQU7zc9UNmXggsln3WvUv92vgOv/q+U9/BxPjIpRAkkTudUIqkrlE1OOu1b1xcRuiT1oQzRjTEi5yVR5stBBc4Rv/RzRN7y92vgh86PVoo2vDJPDXciSthmDntLciXU+Jq7+n3EUL6OKwtwpBP5ZT6KHrNXuMKNevWRHMj3fKUGjUbHrDG364wtggAXY7RRakcGE0i0Hkn+yvWdxE8GJTGiK6gW3jP2qFiGGU5DKaRL9rC1O3EokAa0J0v6VTW+aLuCy9AGkWZ6G274IucZId+SPj03KBBqtUEAZKDRGGOgrS78oJKCj90YJLQn2a2SGUQ2/JEmI97NSANbBv24XztiEPfdG9oabyHHLtfdN68mVuvHgvGvmIO63GtI3abYtTC83jXBzZrgAgZK7cNrh4Y2Thf2y8z+iFXDYWDLrnwFVaAi+KLVDDQbXMeiFWyc="
