language: go

os:
  - linux
  - osx
  - windows

go:
  - "1.12.x"
  - "1.13.x"

install:
  - go get -t ./...

before_script:
  - |
    if [[ $TRAVIS_GO_VERSION == '1.13.x' && $TRAVIS_OS_NAME == 'linux' ]]; then
      curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
    fi

script:
  - go test -v -race ./...
  - |
    if [[ $TRAVIS_GO_VERSION == '1.13.x' && $TRAVIS_OS_NAME == 'linux' ]]; then
      golangci-lint run --exclude-use-default=false
    fi
