name: modver

on:
  pull_request:

permissions:
  contents: read # This gets granted by default, so keep granting it.
  packages: read # This gets granted by default, so keep granting it.
  pull-requests: write # Needed to comment on the PR.

jobs:
  modver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: bobg/modver@62db963a8c1d4c3725a1195bf65b6d957c087c9b # 2.12.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_url: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
